*&---------------------------------------------------------------------*
*&  Include           ZINSPECTION_EXCEL_FORMAT
*&---------------------------------------------------------------------*

TYPE-POOLS OLE2 .

DATA: APPLICATION TYPE OLE2_OBJECT,
      WORKBOOK    TYPE OLE2_OBJECT,
      SHEET       TYPE OLE2_OBJECT,
      CELLS       TYPE OLE2_OBJECT,
      CELL1       TYPE OLE2_OBJECT,
      CELL2       TYPE OLE2_OBJECT,
      RANGE       TYPE OLE2_OBJECT,
      FONT        TYPE OLE2_OBJECT,
      COLUMN      TYPE OLE2_OBJECT,
      SHADING     TYPE OLE2_OBJECT,
      BORDER      TYPE OLE2_OBJECT.
CONSTANTS: ROW_MAX TYPE I VALUE 256.
DATA INDEX TYPE I.
DATA: LD_COLINDX TYPE I,   "COLUMN INDEX
      LD_ROWINDX TYPE I.   "ROW INDEX

TYPES: BEGIN OF T_DATA,
         FIELD1  TYPE STRING,
         FIELD2  TYPE STRING,
         FIELD3  TYPE STRING,
         FIELD4  TYPE STRING,


       END OF T_DATA.

DATA: IT_COL_NO     TYPE STANDARD TABLE OF T_DATA,
      WA_COL_NO     LIKE LINE OF IT_COL_NO,
      IT_HEADER     TYPE STANDARD TABLE OF T_DATA,
      WA_HEADER     LIKE LINE OF IT_HEADER,
      IT_SUB_HEADER TYPE STANDARD TABLE OF T_DATA,
      WA_SUB_HEADER LIKE LINE OF IT_SUB_HEADER,
      IT_DATA       TYPE STANDARD TABLE OF T_DATA,
      WA_DATA       LIKE LINE OF IT_DATA.

*FIELD SYMBOL TO HOLD VALUES
FIELD-SYMBOLS: <FS>.

DATA: BEGIN OF ITAB1 OCCURS 0, FIRST_NAME(10), END OF ITAB1.
DATA: BEGIN OF ITAB2 OCCURS 0, LAST_NAME(10), END OF ITAB2.
DATA: BEGIN OF ITAB3 OCCURS 0, FORMULA(50), END OF ITAB3.
