*************Bill-to Address****************
CLEAR wa_adr.
READ TABLE IT_ADR INTO WA_ADR WITH KEY PARTN_ROLE = 'AG'.

IF SY-SUBRC = 0.
SELECT SINGLE * FROM ADRC INTO WA_BILTO
  WHERE ADDRNUMBER = WA_ADR-ADDR_NO.
ENDIF.

SELECT ADDRNUMBER
       CONSNUMBER
       SMTP_ADDR  FROM adr6 INTO TABLE IT_BEMAIL
       WHERE ADDRNUMBER = WA_ADR-ADDR_NO.
SORT IT_BEMAIL by CONSNUMBER.
LOOP AT IT_BEMAIL INTO WA_BEMAIL.
CONCATENATE gv_bemail WA_BEMAIL-smtp_addr ','  INTO gv_bemail SEPARATED BY Space.
ENDLOOP.

*************Ship-to Address****************
CLEAR wa_adr.
READ TABLE IT_ADR INTO WA_ADR WITH KEY PARTN_ROLE = 'WE'.

IF SY-SUBRC = 0.
SELECT SINGLE * FROM ADRC INTO WA_SHIPTO
  WHERE ADDRNUMBER = WA_ADR-ADDR_NO.
ENDIF.

SELECT ADDRNUMBER
       CONSNUMBER
       SMTP_ADDR  FROM adr6 INTO TABLE IT_SEMAIL
       WHERE ADDRNUMBER = WA_ADR-ADDR_NO.
SORT IT_SEMAIL by CONSNUMBER.
LOOP AT IT_SEMAIL INTO WA_SEMAIL.
CONCATENATE gv_semail WA_SEMAIL-smtp_addr ','  INTO gv_semail SEPARATED BY Space.
ENDLOOP.

*************Sale Rep Name****************
CLEAR wa_adr.
READ TABLE IT_ADR INTO WA_ADR WITH KEY PARTN_ROLE = 'UR'.

IF sy-subrc = 0.
SELECT SINGLE * FROM KNA1 INTO WA_KNA1
  WHERE KUNNR = WA_ADR-PARTN_NUMB.
ENDIF.

















