*&---------------------------------------------------------------------*
*& Report ZUS_FI_STOCK_PLANNING
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZUS_FI_STOCK_PLANNING.



TABLES : MARA,MARD,MSEG,EKPO,EKET,VBBE,MSKU.

TYPES : BEGIN OF TY_MARA,
          MATNR   TYPE MARA-MATNR,
          ZSERIES TYPE MARA-ZSERIES,
          ZSIZE   TYPE MARA-ZSIZE,
          BRAND   TYPE MARA-BRAND,
          MOC     TYPE MARA-MOC,
          TYPE    TYPE MARA-TYPE,
          WRKST   TYPE MARA-WRKST,
*          bwart   TYPE mara-bwart,
        END OF TY_MARA.

DATA : IT_MARA TYPE STANDARD TABLE OF TY_MARA,
       WA_MARA TYPE TY_MARA.

TYPES : BEGIN OF TY_VBBE,
          MATNR TYPE VBBE-MATNR,
          WERKS TYPE VBBE-WERKS,
          OMENG TYPE VBBE-OMENG,
        END OF TY_VBBE.

DATA : IT_VBBE TYPE STANDARD TABLE OF TY_VBBE,
       WA_VBBE TYPE TY_VBBE.

TYPES : BEGIN OF TY_MARD,
          MATNR TYPE MARD-MATNR,
          LGORT TYPE MARD-LGORT,
          WERKS TYPE MARD-WERKS,
          LABST TYPE MARD-LABST,
        END OF TY_MARD.

DATA : IT_MARD TYPE STANDARD TABLE OF TY_MARD,
       WA_MARD TYPE TY_MARD.

TYPES : BEGIN OF TY_MSKU,
          MATNR TYPE MSKU-MATNR,
          WERKS TYPE MSKU-WERKS,
          CHARG TYPE MSKU-CHARG,
          SOBKZ TYPE MSKU-SOBKZ,
          KUNNR TYPE MSKU-KUNNR,
          KULAB TYPE MSKU-KULAB,
        END OF TY_MSKU.

DATA : IT_MSKU TYPE STANDARD TABLE OF TY_MSKU,
       WA_MSKU TYPE TY_MSKU.

TYPES : BEGIN OF TY_MSEG,
          MATNR    TYPE MSEG-MATNR,
          MBLNR    TYPE MSEG-MBLNR,
          ZEILE    TYPE MSEG-ZEILE,
          BWART    TYPE MSEG-BWART,
          WERKS    TYPE MSEG-WERKS,
          VBELN_IM TYPE MSEG-VBELN_IM,
          VBELP_IM TYPE MSEG-VBELP_IM,
          MENGE    TYPE MSEG-MENGE,
          EBELN    TYPE MSEG-EBELN,
          EBELP    TYPE MSEG-EBELP,
        END OF TY_MSEG.

DATA : IT_MSEG TYPE STANDARD TABLE OF TY_MSEG,
       WA_MSEG TYPE TY_MSEG.

TYPES: BEGIN OF TY_TRANSIT,
         EBELN TYPE EKPO-EBELN,
         EBELP TYPE EKPO-EBELP,
         MATNR TYPE EKPO-MATNR,
         WERKS TYPE EKPO-WERKS,
         NETPR TYPE EKPO-NETPR,
       END OF TY_TRANSIT.

DATA: IT_TRANSIT TYPE TABLE OF TY_TRANSIT,
      WA_TRANSIT TYPE          TY_TRANSIT.


TYPES: BEGIN OF TY_KONV,
         KNUMV TYPE prcd_elements-KNUMV,
         KPOSN TYPE prcd_elements-KPOSN,
         KSCHL TYPE prcd_elements-KSCHL,
         KBETR TYPE prcd_elements-KBETR,
       END OF TY_KONV.

DATA: IT_KONV TYPE TABLE OF TY_KONV,
      WA_KONV TYPE          TY_KONV.

TYPES : BEGIN OF TY_REV,
          MBLNR   TYPE MSEG-MBLNR,
          ZEILE   TYPE MSEG-ZEILE,
          LINE_ID TYPE MSEG-LINE_ID,
          BWART   TYPE MSEG-BWART,
          MATNR   TYPE MSEG-MATNR,
          WERKS   TYPE MSEG-WERKS,
          MENGE   TYPE MSEG-MENGE,
          SMBLN   TYPE MSEG-SMBLN,
        END OF TY_REV.

DATA : IT_REV TYPE STANDARD TABLE OF TY_REV,
       WA_REV TYPE TY_REV.

DATA : IT_REV1 TYPE STANDARD TABLE OF TY_REV,
       WA_REV1 TYPE TY_REV.

DATA : IT_MSEG_105 TYPE STANDARD TABLE OF TY_MSEG,
       WA_MSEG_105 TYPE TY_MSEG.

TYPES : BEGIN OF TY_GRN,
          MATNR    TYPE MSEG-MATNR,
          MBLNR    TYPE MSEG-MBLNR,
          ZEILE    TYPE MSEG-ZEILE,
          BWART    TYPE MSEG-BWART,
          WERKS    TYPE MSEG-WERKS,
          VBELN_IM TYPE MSEG-VBELN_IM,
          VBELP_IM TYPE MSEG-VBELP_IM,
          MENGE    TYPE MSEG-MENGE,
          DMBTR    TYPE MSEG-DMBTR,
          KZBEW    TYPE MSEG-KZBEW,
          SMBLN    TYPE MSEG-SMBLN,
        END OF TY_GRN.

DATA : IT_GRN TYPE TABLE OF TY_GRN,
       WA_GRN TYPE TY_GRN.

DATA : IT_GRN_REV TYPE TABLE OF TY_GRN,
       WA_GRN_REV TYPE          TY_GRN.


TYPES: BEGIN OF TY_EKPO,
         MATNR TYPE EKPO-MATNR,
         EBELN TYPE EKPO-EBELN,
         EBELP TYPE EKPO-EBELP,
         MENGE TYPE EKPO-MENGE,
         LOEKZ TYPE EKPO-LOEKZ,
         ELIKZ TYPE EKPO-ELIKZ,
         WERKS TYPE EKPO-WERKS,
         RETPO TYPE EKPO-RETPO,
         BRTWR TYPE EKPO-BRTWR,
       END OF TY_EKPO.
*
*DATA : it_ekpo TYPE STANDARD TABLE OF ty_ekpo,
*       wa_ekpo TYPE ty_ekpo.
*
DATA : IT_EKPO1 TYPE STANDARD TABLE OF TY_EKPO,
       WA_EKPO1 TYPE TY_EKPO.

TYPES : BEGIN OF TY_EKPO_EKET,

          EBELN TYPE EKPO-EBELN,
          EBELP TYPE EKPO-EBELP,
          MATNR TYPE EKPO-MATNR,
          MENGE TYPE EKPO-MENGE,
          LOEKZ TYPE EKPO-LOEKZ,
          ELIKZ TYPE EKPO-ELIKZ,
          WERKS TYPE EKPO-WERKS,
          RETPO TYPE EKPO-RETPO,
          BRTWR TYPE EKPO-BRTWR,
          WEMNG TYPE EKET-WEMNG,
        END OF TY_EKPO_EKET.

DATA : IT_EKPO_EKET TYPE STANDARD TABLE OF TY_EKPO_EKET,
       WA_EKPO_EKET TYPE TY_EKPO_EKET.

TYPES : BEGIN OF TY_VBAP,
          VBELN  TYPE VBAP-VBELN,
          POSNR  TYPE VBAP-POSNR,
          MATNR  TYPE VBAP-MATNR,
          WERKS  TYPE VBAP-WERKS,
          KWMENG TYPE VBAP-KWMENG,
        END OF TY_VBAP.

DATA: IT_VBAP TYPE TABLE OF TY_VBAP,
      WA_VBAP TYPE          TY_VBAP.

TYPES :BEGIN OF TY_VBUP,
         VBELN TYPE VBUP-VBELN,
         POSNR TYPE VBUP-POSNR,
         LFGSA TYPE VBUP-LFGSA,
       END OF TY_VBUP.

DATA :IT_VBUP TYPE TABLE OF TY_VBUP,
      WA_VBUP TYPE          TY_VBUP.

TYPES : BEGIN OF TY_LIPS,
          VBELN TYPE LIPS-VBELN,
          POSNR TYPE LIPS-POSNR,
          VGBEL TYPE LIPS-VGBEL,
          VGPOS TYPE LIPS-VGPOS,
          MATNR TYPE LIPS-MATNR,
          WERKS TYPE LIPS-WERKS,
          LFIMG TYPE LIPS-LFIMG,
        END OF TY_LIPS.

DATA: IT_LIPS TYPE TABLE OF TY_LIPS,
      WA_LIPS TYPE          TY_LIPS.


TYPES : BEGIN OF TY_MARA_MARD,
          MATNR   TYPE MARA-MATNR,
          ZSERIES TYPE MARA-ZSERIES,
          ZSIZE   TYPE MARA-ZSIZE,
          BRAND   TYPE MARA-BRAND,
          MOC     TYPE MARA-MOC,
          TYPE    TYPE MARA-TYPE,
          WRKST   TYPE MARA-WRKST,
          WERKS   TYPE MARD-WERKS,
        END OF TY_MARA_MARD.

DATA : IT_MARA_MARD TYPE STANDARD TABLE OF TY_MARA_MARD,
       WA_MARA_MARD TYPE TY_MARA_MARD.

TYPES : BEGIN OF TY_VBAK,
          VBELN TYPE VBAK-VBELN,
          VBTYP TYPE VBAK-VBTYP,
          KNUMV TYPE VBAK-KNUMV,
        END OF TY_VBAK.

DATA : IT_VBAK TYPE TABLE OF TY_VBAK,
       WA_VBAK TYPE TY_VBAK.

TYPES: BEGIN OF TY_MBEW,
         MATNR TYPE MBEW-MATNR,
         BWKEY TYPE MBEW-BWKEY,
         SALK3 TYPE MBEW-SALK3,
         VPRSV TYPE MBEW-VPRSV,
         VERPR TYPE MBEW-VERPR,
         STPRS TYPE MBEW-STPRS,
       END OF TY_MBEW.

DATA: IT_MBEW TYPE TABLE OF TY_MBEW,
      WA_MBEW TYPE          TY_MBEW.

TYPES: BEGIN OF TY_DATA,
         VBELN  TYPE VBELN,
         POSNR  TYPE POSNR,
         MATNR  TYPE MATNR,
         WERKS  TYPE WERKS,
         KWMENG TYPE KWMENG,
         ABGRU  TYPE ABGRU,
         PSTYV  TYPE PSTYV,
       END OF TY_DATA.

DATA: IT_DATA TYPE STANDARD TABLE OF TY_DATA,
      WA_DATA TYPE TY_DATA.

TYPES: BEGIN OF TY_OPEN_INV,
         VBELN TYPE LIPS-VBELN,
         POSNR TYPE LIPS-POSNR,
         MATNR TYPE LIPS-MATNR,
         WERKS TYPE LIPS-WERKS,
         LFIMG TYPE LIPS-LFIMG,
         VKBUR TYPE LIPS-VKBUR,
         FKSTA TYPE VBUP-FKSTA,
       END OF TY_OPEN_INV.

DATA: IT_OPEN_INV TYPE TABLE OF TY_OPEN_INV,
      WA_OPEN_INV TYPE          TY_OPEN_INV.
TYPES : BEGIN OF TY_FINAL,
          MATNR         TYPE MARA-MATNR,
          ZSERIES       TYPE MARA-ZSERIES,
          ZSIZE         TYPE MARA-ZSIZE,
          BRAND         TYPE MARA-BRAND,
          MOC           TYPE MARA-MOC,
          TYPE          TYPE MARA-TYPE,
          WRKST         TYPE MARA-WRKST,

          VBELN         TYPE VBAP-VBELN,
          POSNR         TYPE VBAP-POSNR,
          LFGSA         TYPE VBUP-LFGSA,

          VGBEL         TYPE LIPS-VGBEL,
          VGPOS         TYPE LIPS-VGPOS,
          LFIMG         TYPE LIPS-LFIMG,

          WERKS         TYPE MARD-WERKS,
          LABST         TYPE P DECIMALS 0,

          OMENG         TYPE VBBE-OMENG,

          KULAB         TYPE P DECIMALS 0,

          BWART         TYPE MSEG-BWART,
          VBELN_IM      TYPE MSEG-VBELN_IM,
          VBELP_IM      TYPE MSEG-VBELP_IM,
          MSEG_MENGE    TYPE MSEG-MENGE,
          MSEG_MENGE1   TYPE MSEG-MENGE,
          MBLNR         TYPE MSEG-MBLNR,
          SMBLN         TYPE MSEG-SMBLN,

          EBELN         TYPE EKPO-EBELN,
          EBELP         TYPE EKPO-EBELP,
          MENGE         TYPE EKPO-MENGE,
          LOEKZ         TYPE EKPO-LOEKZ,
          ELIKZ         TYPE EKPO-ELIKZ,

          WEMNG         TYPE EKET-WEMNG,
*          lv_desc     TYPE tdline,
          MATTXT        TYPE TEXT100,
          FREE_STOCK    TYPE P DECIMALS 0,
          TRAN_QTY      TYPE P DECIMALS 0,
          SO_FALL_QTY   TYPE P DECIMALS 0,
          MENGE2        TYPE STRING,
          MENGE3        TYPE STRING,
          MENGE4        TYPE STRING,
*          pend_po_qty TYPE string,
          PEND_PO_QTY   TYPE P DECIMALS 0,
          INDENT_QTY    TYPE P DECIMALS 0,
          OPEN_QTY      TYPE P DECIMALS 0,
          VBAP_QTY      TYPE VBRP-FKIMG,
          LIPS_QTY      TYPE VBRP-FKIMG,
          RETPO         TYPE EKPO-RETPO,
          NEG           TYPE STRING,
          OPEN_INV      TYPE P DECIMALS 0,
          VALUE         TYPE MSEG-DMBTR,
          OPEN_QTY_V    TYPE MSEG-DMBTR,
          LABST_V       TYPE MSEG-DMBTR,
          KULAB_V       TYPE MSEG-DMBTR,
          FREE_STOCK_V  TYPE MSEG-DMBTR,
          TRAN_QTY_V    TYPE MSEG-DMBTR,
          SO_FALL_QTY_V TYPE MSEG-DMBTR,
          PEND_PO_QTY_V TYPE MSEG-DMBTR,
          INDENT_QTY_V  TYPE MSEG-DMBTR,
          OPEN_INV_V    TYPE MSEG-DMBTR,
          AMOUNT        TYPE MSEG-DMBTR,
          PRICE         TYPE MSEG-DMBTR,
          PO_VAL        TYPE EKPO-BRTWR,
          PO_VAL1       TYPE EKPO-BRTWR,
          PO_VAL2       TYPE EKPO-BRTWR,
          PO_VALUE      TYPE EKPO-BRTWR,
          GRN_VALUE     TYPE MSEG-DMBTR,
          UN_QTY        TYPE P DECIMALS 0,
          UN_VAL        TYPE MSEG-DMBTR,
*          LABST_V     TYPE mseg-dmbtr,
          PSTYV         TYPE PSTYV,
        END OF TY_FINAL.

DATA : IT_FINAL TYPE STANDARD TABLE OF TY_FINAL,
       WA_FINAL TYPE TY_FINAL.

TYPES : BEGIN OF TY_FINAL_DOWNLOAD,
          MATNR         TYPE MARA-MATNR,
          MATTXT        TYPE TEXT100,
          WRKST         TYPE MARA-WRKST,
          BRAND         TYPE MARA-BRAND,
          ZSERIES       TYPE MARA-ZSERIES,
          ZSIZE         TYPE MARA-ZSIZE,
          MOC           TYPE MARA-MOC,
          TYPE          TYPE MARA-TYPE,
          OPEN_QTY      TYPE CHAR15,
          PRICE         TYPE CHAR15,
          UN_QTY        TYPE CHAR15,
          UN_VAL        TYPE CHAR15,
          OPEN_QTY_V    TYPE CHAR15,
          LABST         TYPE CHAR15,
          LABST_V       TYPE CHAR15,
          KULAB         TYPE CHAR15,
          KULAB_V       TYPE CHAR15,
          FREE_STOCK    TYPE CHAR15,
          FREE_STOCK_V  TYPE CHAR15,
          TRAN_QTY      TYPE CHAR15,
          TRAN_QTY_V    TYPE CHAR15,
          SO_FALL_QTY   TYPE CHAR15,
          SO_FALL_QTY_V TYPE CHAR15,
          PEND_PO_QTY   TYPE CHAR15,
          PO_VALUE      TYPE CHAR15,
*          indent_qty    TYPE char15,
*          INDENT_QTY_V  TYPE char15,
          OPEN_INV      TYPE CHAR15,
          AMOUNT        TYPE CHAR15,
          VALUE         TYPE CHAR15,
          REF           TYPE CHAR15,
          WERKS         TYPE CHAR10,
        END OF TY_FINAL_DOWNLOAD.

DATA : LT_FINAL TYPE TABLE OF TY_FINAL_DOWNLOAD,
       LS_FINAL TYPE TY_FINAL_DOWNLOAD.

DATA  : GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV,
        GS_FIELDCAT TYPE SLIS_FIELDCAT_ALV.

DATA : GT_LINES TYPE TABLE OF TLINE,
       LS_LINES TYPE TLINE.

DATA : LV_DESC TYPE TLINE.

DATA : PR_COUNT TYPE I.

DATA : NEG TYPE STRING.
DATA: LV_NAME   TYPE THEAD-TDNAME,
      LV_LINES  TYPE STANDARD TABLE OF TLINE,
      WA_LINES  LIKE TLINE,
      LS_ITMTXT TYPE TLINE,
      LS_MATTXT TYPE TLINE.

SELECTION-SCREEN : BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
SELECT-OPTIONS : MAT FOR MARA-MATNR,
                 PLANT FOR MARD-WERKS OBLIGATORY DEFAULT 'US01'.
*PARAMETERS: PLANT LIKE MARD-WERKS DEFAULT 'US01'.
SELECTION-SCREEN : END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002 .
PARAMETERS P_DOWN AS CHECKBOX.
PARAMETERS P_FOLDER LIKE RLGRAP-FILENAME DEFAULT '/Delval/USA'."USA'."usa'."'E:/delval/usa'.
SELECTION-SCREEN END OF BLOCK B2.

LOOP AT plant.
IF plant-low = 'PL01'.
   plant-low = ' '.
ENDIF.
IF plant-high = 'PL01'.
   plant-high = ' '.
ENDIF.
MODIFY plant.
ENDLOOP.



START-OF-SELECTION.

    PERFORM GET_DATA.
    PERFORM PROCESS_DATA.
*  PERFORM get_matdesc.
    PERFORM FCAT.
    PERFORM DISPLAY_DATA.

FORM GET_DATA .

  SELECT
    A~MATNR
    A~ZSERIES
    A~ZSIZE
    A~BRAND
    A~MOC
    A~TYPE
    A~WRKST
    B~WERKS
    INTO TABLE IT_MARA_MARD
    FROM MARA AS A
    INNER JOIN MARD AS B ON B~MATNR = A~MATNR
    WHERE A~MATNR IN MAT AND B~WERKS IN PLANT.

  SORT it_mara_mard BY matnr werks.
  DELETE ADJACENT DUPLICATES FROM IT_MARA_MARD COMPARING MATNR WERKS.

DELETE IT_MARA_MARD WHERE werks = 'PL01'.
  SELECT A~VBELN A~POSNR A~MATNR A~WERKS A~KWMENG A~ABGRU A~PSTYV
      INTO TABLE IT_DATA
      FROM  VBAP AS A
      JOIN  VBUP AS B ON ( B~VBELN = A~VBELN  AND B~POSNR = A~POSNR )
      FOR ALL ENTRIES IN IT_MARA_MARD
      WHERE A~MATNR = IT_MARA_MARD-MATNR
      AND   A~WERKS  = IT_MARA_MARD-WERKS
      AND   A~ABGRU = ''
      AND   B~LFSTA  NE 'C'.


  SELECT A~VBELN A~POSNR A~MATNR A~WERKS A~LFIMG A~VKBUR B~FKSTA
      INTO TABLE IT_OPEN_INV
      FROM  LIPS AS A
      JOIN  VBUP AS B ON ( B~VBELN = A~VBELN  AND B~POSNR = A~POSNR )
      FOR ALL ENTRIES IN IT_MARA_MARD
      WHERE A~MATNR = IT_MARA_MARD-MATNR
      AND   A~WERKS  = IT_MARA_MARD-WERKS
      AND   A~VKBUR  = 'US01'
      AND   B~FKSTA  NE 'C'.

  SELECT
    VBELN
    VBTYP
    KNUMV
    FROM VBAK
    INTO TABLE IT_VBAK
    FOR ALL ENTRIES IN IT_DATA
    WHERE VBELN = IT_DATA-VBELN
    AND   VBTYP IN ( 'C' , 'I' , 'H' ).


  IF IT_VBAK IS NOT INITIAL.
    SELECT KNUMV
           KPOSN
           KSCHL
           KBETR FROM prcd_elements INTO TABLE IT_KONV
           FOR ALL ENTRIES IN IT_VBAK
           WHERE KNUMV = IT_VBAK-KNUMV
            AND  KSCHL = 'ZPR0'.
  ENDIF.

  SELECT
    VBELN
    POSNR
    VGBEL
    VGPOS
    MATNR
    WERKS
    LFIMG
    FROM LIPS
    INTO TABLE IT_LIPS
           FOR ALL ENTRIES IN IT_DATA
           WHERE VGBEL = IT_DATA-VBELN
            AND  VGPOS = IT_DATA-POSNR.

  IF IT_MARA_MARD IS NOT INITIAL.
    SELECT MATNR
           ZSERIES
           ZSIZE
           BRAND
           MOC
           TYPE
           WRKST   FROM MARA INTO TABLE IT_MARA
           FOR ALL ENTRIES IN IT_MARA_MARD
           WHERE MATNR = IT_MARA_MARD-MATNR.


    SELECT
            MATNR
            LGORT
            WERKS
            LABST
            FROM MARD
            INTO TABLE IT_MARD
            FOR ALL ENTRIES IN IT_MARA_MARD
            WHERE MATNR = IT_MARA_MARD-MATNR
            AND WERKS = IT_MARA_MARD-WERKS.

    SELECT MATNR
           BWKEY
           SALK3
           VPRSV
           VERPR
           STPRS FROM MBEW INTO TABLE IT_MBEW
           FOR ALL ENTRIES IN IT_MARA_MARD
           WHERE MATNR = IT_MARA_MARD-MATNR
           AND BWKEY = IT_MARA_MARD-WERKS.


  ENDIF.

  IF IT_MARA_MARD IS NOT INITIAL.
    SELECT
      MATNR
      WERKS
      OMENG
      FROM VBBE
      INTO TABLE IT_VBBE
      FOR ALL ENTRIES IN IT_MARA_MARD
      WHERE MATNR EQ IT_MARA_MARD-MATNR AND WERKS EQ IT_MARA_MARD-WERKS.
  ENDIF.

  IF IT_MARA_MARD IS NOT INITIAL .
    SELECT MATNR
           WERKS
           CHARG
           SOBKZ
           KUNNR
           KULAB FROM MSKU
           INTO TABLE IT_MSKU
           FOR ALL ENTRIES IN IT_MARA_MARD
           WHERE MATNR EQ IT_MARA_MARD-MATNR.
  ENDIF.

  IF IT_MARA_MARD IS NOT INITIAL .
    SELECT EBELN
           EBELP
           MATNR
           WERKS
           NETPR FROM EKPO INTO TABLE IT_TRANSIT
           FOR ALL ENTRIES IN IT_MARA_MARD
           WHERE MATNR = IT_MARA_MARD-MATNR
           AND   WERKS = IT_MARA_MARD-WERKS.
  ENDIF.



  IF IT_TRANSIT IS NOT INITIAL .
    SELECT
      MATNR
      MBLNR
      ZEILE
      BWART
      WERKS
      VBELN_IM
      VBELP_IM
      MENGE
      EBELN
      EBELP
      FROM MSEG
      INTO TABLE IT_MSEG
      FOR ALL ENTRIES IN IT_TRANSIT
      WHERE MATNR = IT_TRANSIT-MATNR
      AND   WERKS = IT_TRANSIT-WERKS
      AND   EBELN = IT_TRANSIT-EBELN
      AND   EBELP = IT_TRANSIT-EBELP
      AND BWART = '103'.
  ENDIF.

  IF IT_TRANSIT IS NOT INITIAL .
    SELECT
      MATNR
      MBLNR
      ZEILE
      BWART
      WERKS
      VBELN_IM
      VBELP_IM
      MENGE
      EBELN
      EBELP
      FROM MSEG
      INTO TABLE IT_MSEG_105
      FOR ALL ENTRIES IN IT_TRANSIT
      WHERE MATNR = IT_TRANSIT-MATNR
      AND   WERKS = IT_TRANSIT-WERKS
      AND   EBELN = IT_TRANSIT-EBELN
      AND   EBELP = IT_TRANSIT-EBELP
      AND BWART = '105'.
  ENDIF.

  IF IT_MARA_MARD IS NOT INITIAL.

    SELECT MATNR
           MBLNR
           ZEILE
           BWART
           WERKS
           VBELN_IM
           VBELP_IM
           MENGE
           DMBTR
           KZBEW
           SMBLN  FROM MSEG
           INTO TABLE IT_GRN
           FOR ALL ENTRIES IN IT_MARA_MARD
           WHERE MATNR = IT_MARA_MARD-MATNR
           AND   WERKS = IT_MARA_MARD-WERKS
           AND BWART IN ( '101' , '105' )
           AND KZBEW NE 'F'.

  ENDIF.

  IF IT_GRN IS NOT INITIAL.
    SELECT MATNR
           MBLNR
           ZEILE
           BWART
           WERKS
           VBELN_IM
           VBELP_IM
           MENGE
           DMBTR
           KZBEW
           SMBLN  FROM MSEG
           INTO TABLE IT_GRN_REV
           FOR ALL ENTRIES IN IT_GRN
           WHERE SMBLN = IT_GRN-MBLNR
            AND  MATNR = IT_GRN-MATNR.


  ENDIF.

  SORT IT_GRN DESCENDING BY MBLNR.

  IF IT_MSEG IS NOT INITIAL.
    SELECT MBLNR
           ZEILE
           LINE_ID
           BWART
           MATNR
           WERKS
           MENGE
           SMBLN  FROM MSEG INTO TABLE IT_REV
           FOR ALL ENTRIES IN IT_MSEG
           WHERE SMBLN = IT_MSEG-MBLNR
            AND  MATNR = IT_MSEG-MATNR.
  ENDIF.

  IF IT_MSEG_105 IS NOT INITIAL.
    SELECT MBLNR
           ZEILE
           LINE_ID
           BWART
           MATNR
           WERKS
           MENGE
           SMBLN
      FROM MSEG INTO TABLE IT_REV1
           FOR ALL ENTRIES IN IT_MSEG_105
           WHERE SMBLN = IT_MSEG_105-MBLNR
            AND  MATNR = IT_MSEG_105-MATNR.
  ENDIF.


  SELECT A~EBELN
         A~EBELP
         A~MATNR
         A~MENGE
         A~LOEKZ
         A~ELIKZ
         A~WERKS
         A~RETPO
         A~BRTWR
         B~WEMNG
         INTO TABLE IT_EKPO_EKET
         FROM EKPO AS A
         INNER JOIN EKET AS B
         ON A~EBELN = B~EBELN
         AND A~EBELP = B~EBELP
         FOR ALL ENTRIES IN IT_MARA_MARD
         WHERE A~MATNR EQ IT_MARA_MARD-MATNR AND A~WERKS EQ IT_MARA_MARD-WERKS
         AND A~LOEKZ NE 'L' AND A~RETPO NE 'X'.



  IF IT_MARA_MARD IS NOT INITIAL .
    SELECT MATNR
           EBELN
           EBELP
           MENGE
           LOEKZ
           ELIKZ
           WERKS
           RETPO
           BRTWR
           FROM EKPO
           INTO TABLE IT_EKPO1
           FOR ALL ENTRIES IN IT_MARA_MARD
           WHERE MATNR EQ IT_MARA_MARD-MATNR
           AND WERKS EQ IT_MARA_MARD-WERKS
           AND RETPO EQ 'X'.
  ENDIF.

ENDFORM.

FORM PROCESS_DATA .

  SORT IT_EKPO1 .

  LOOP AT IT_MARA_MARD INTO WA_MARA_MARD.
*  LOOP AT IT_MARA INTO WA_MARA.

*    READ TABLE IT_MARA_MARD INTO WA_MARA_MARD WITH KEY MATNR = WA_MARA-MATNR.
*    IF SY-SUBRC = 0.
      WA_FINAL-MATNR   = WA_MARA_MARD-MATNR  .
      WA_FINAL-ZSERIES = WA_MARA_MARD-ZSERIES.
      WA_FINAL-ZSIZE   = WA_MARA_MARD-ZSIZE  .
      WA_FINAL-BRAND   = WA_MARA_MARD-BRAND  .
      WA_FINAL-MOC     = WA_MARA_MARD-MOC    .
      WA_FINAL-TYPE    = WA_MARA_MARD-TYPE   .
      WA_FINAL-WRKST   = WA_MARA_MARD-WRKST  .
      WA_FINAL-WERKS   = WA_MARA_MARD-WERKS  .

*    ENDIF.

    READ TABLE IT_MBEW INTO WA_MBEW WITH KEY MATNR = WA_MARA_MARD-MATNR  BWKEY = WA_MARA_MARD-WERKS.
    IF SY-SUBRC = 0.
      IF WA_MBEW-VPRSV = 'V'.
        WA_FINAL-VALUE = WA_MBEW-VERPR.
      ELSE .
        WA_FINAL-VALUE = WA_MBEW-STPRS.
      ENDIF.
      WA_FINAL-LABST_V = WA_MBEW-SALK3.
      WA_FINAL-UN_VAL  = WA_MBEW-SALK3.
    ENDIF.


    CLEAR WA_FINAL-LABST.
    LOOP AT IT_MARD INTO WA_MARD WHERE MATNR = WA_MARA_MARD-MATNR AND WERKS = WA_MARA_MARD-WERKS.
      WA_FINAL-LABST = WA_FINAL-LABST + WA_MARD-LABST.
      WA_FINAL-UN_QTY = WA_FINAL-UN_QTY + WA_MARD-LABST.
    ENDLOOP.

    CLEAR WA_VBAP.
    CLEAR WA_VBUP.
    CLEAR WA_LIPS.
    CLEAR WA_FINAL-VBAP_QTY.
    CLEAR WA_VBAP-KWMENG.

    LOOP AT IT_OPEN_INV INTO WA_OPEN_INV WHERE MATNR = WA_MARA_MARD-MATNR AND WERKS = WA_MARA_MARD-WERKS..
      WA_FINAL-OPEN_INV = WA_FINAL-OPEN_INV + WA_OPEN_INV-LFIMG.
    ENDLOOP.

    CLEAR WA_VBAK.
    CLEAR WA_FINAL-LIPS_QTY.
    CLEAR WA_LIPS-LFIMG.

    DATA:QTY     TYPE VBAP-KWMENG,
         DEL     TYPE VBAP-KWMENG,
         PENDING TYPE VBAP-KWMENG,
         PRICE   TYPE prcd_elements-KBETR.
    CLEAR: QTY,PRICE.

    LOOP AT IT_DATA INTO WA_DATA WHERE MATNR = WA_MARA_MARD-MATNR AND WERKS = WA_MARA_MARD-WERKS.
      CLEAR: QTY,PRICE,PENDING,DEL.
      WA_FINAL-VBELN = WA_DATA-VBELN.
      WA_FINAL-POSNR = WA_DATA-POSNR.
      READ TABLE IT_VBAK INTO WA_VBAK WITH KEY VBELN = WA_DATA-VBELN.
      IF SY-SUBRC = 0.
        WA_FINAL-VBAP_QTY = WA_FINAL-VBAP_QTY + WA_DATA-KWMENG.
        QTY = QTY + WA_DATA-KWMENG.
      ENDIF.

      READ TABLE IT_KONV INTO WA_KONV WITH KEY KNUMV = WA_VBAK-KNUMV KPOSN = WA_DATA-POSNR.
      IF SY-SUBRC = 0.

      ENDIF.


      LOOP AT IT_LIPS INTO WA_LIPS WHERE VGBEL = WA_FINAL-VBELN AND  VGPOS = WA_FINAL-POSNR.
        WA_FINAL-LIPS_QTY = WA_FINAL-LIPS_QTY + WA_LIPS-LFIMG.
        DEL = DEL + WA_LIPS-LFIMG.
      ENDLOOP.
      IF WA_DATA-PSTYV <> 'ZKLN'.
        PENDING = QTY - DEL.
        PRICE = PENDING * WA_KONV-KBETR.
        WA_FINAL-PRICE = WA_FINAL-PRICE + PRICE.
      ENDIF.

    ENDLOOP.



    CLEAR WA_FINAL-OPEN_QTY.

    WA_FINAL-OPEN_QTY = WA_FINAL-VBAP_QTY - WA_FINAL-LIPS_QTY .


*    READ TABLE it_msku INTO wa_msku WITH KEY matnr = wa_mara_mard-matnr.
*    IF sy-subrc = 0.
*      wa_final-kulab = wa_msku-kulab.
*    ENDIF.
    LOOP AT IT_MSKU INTO WA_MSKU WHERE MATNR = WA_MARA_MARD-MATNR AND WERKS = WA_MARA_MARD-WERKS.
      WA_FINAL-KULAB = WA_FINAL-KULAB + WA_MSKU-KULAB.
    ENDLOOP.
*********************** GRN Amount ********************************

    READ TABLE IT_GRN INTO WA_GRN WITH KEY MATNR = WA_MARA_MARD-MATNR WERKS = WA_MARA_MARD-WERKS.
    IF SY-SUBRC = 0.
      WA_FINAL-AMOUNT = WA_GRN-DMBTR / WA_GRN-MENGE .
    ENDIF.

    LOOP AT IT_GRN INTO WA_GRN WHERE MATNR = WA_MARA_MARD-MATNR AND WERKS = WA_MARA_MARD-WERKS.
      READ TABLE IT_GRN_REV INTO WA_GRN_REV WITH KEY SMBLN = WA_GRN-MBLNR MATNR = WA_GRN-MATNR.
      IF SY-SUBRC = 4.
        WA_FINAL-GRN_VALUE = WA_FINAL-GRN_VALUE + WA_GRN-DMBTR.
      ENDIF.
    ENDLOOP.



    DATA:TRAN_VAL  TYPE MSEG-DMBTR,
         TRAN_QTY  TYPE MSEG-MENGE,
         MSEG_QTY  TYPE MSEG-MENGE,
         MSEG_QTY1 TYPE MSEG-MENGE.


    LOOP AT IT_TRANSIT INTO WA_TRANSIT WHERE MATNR = WA_MARA_MARD-MATNR AND WERKS = WA_MARA_MARD-WERKS..
      CLEAR: TRAN_VAL,TRAN_QTY,MSEG_QTY ,MSEG_QTY1.
      LOOP AT IT_MSEG INTO WA_MSEG WHERE EBELN = WA_TRANSIT-EBELN AND EBELP = WA_TRANSIT-EBELP AND
                                         MATNR = WA_TRANSIT-MATNR AND WERKS = WA_TRANSIT-WERKS .

        READ TABLE IT_REV INTO WA_REV WITH KEY SMBLN = WA_MSEG-MBLNR MATNR = WA_MSEG-MATNR.
        IF SY-SUBRC = 4.
          WA_FINAL-MSEG_MENGE = WA_FINAL-MSEG_MENGE  + WA_MSEG-MENGE.
          MSEG_QTY   = MSEG_QTY  + WA_MSEG-MENGE.
        ENDIF.
      ENDLOOP.

      LOOP AT IT_MSEG_105 INTO WA_MSEG_105 WHERE  EBELN = WA_TRANSIT-EBELN AND EBELP = WA_TRANSIT-EBELP AND
                                                  MATNR = WA_TRANSIT-MATNR AND WERKS = WA_TRANSIT-WERKS .

        READ TABLE IT_REV1 INTO WA_REV1 WITH KEY SMBLN = WA_MSEG_105-MBLNR MATNR = WA_MSEG_105-MATNR.
        IF SY-SUBRC = 4.
          WA_FINAL-MSEG_MENGE1 = WA_FINAL-MSEG_MENGE1  + WA_MSEG_105-MENGE.
          MSEG_QTY1 = MSEG_QTY1  + WA_MSEG_105-MENGE.
        ENDIF.
      ENDLOOP.



      TRAN_QTY = MSEG_QTY - MSEG_QTY1.
      IF MSEG_QTY IS NOT INITIAL.
        TRAN_VAL = TRAN_QTY * WA_TRANSIT-NETPR.
      ENDIF.
      WA_FINAL-TRAN_QTY_V = WA_FINAL-TRAN_QTY_V + TRAN_VAL.

    ENDLOOP.
    CLEAR WA_FINAL-TRAN_QTY.
    WA_FINAL-TRAN_QTY = WA_FINAL-MSEG_MENGE - WA_FINAL-MSEG_MENGE1.
    CLEAR WA_FINAL-MENGE2.
    CLEAR WA_FINAL-MENGE3.
    CLEAR WA_FINAL-MENGE4.

    CLEAR WA_EKPO1-MENGE.
    CLEAR WA_EKPO_EKET.



    LOOP AT IT_EKPO_EKET INTO WA_EKPO_EKET WHERE MATNR = WA_MARA_MARD-MATNR AND WERKS = WA_MARA_MARD-WERKS.
      IF WA_EKPO_EKET-ELIKZ NE 'X' OR WA_EKPO_EKET-WEMNG NE 0.

        WA_FINAL-MENGE2 = WA_FINAL-MENGE2 + WA_EKPO_EKET-MENGE.
        WA_FINAL-PO_VAL = WA_FINAL-PO_VAL + WA_EKPO_EKET-BRTWR.

      ENDIF.

      WA_FINAL-MENGE3 = WA_FINAL-MENGE3 + WA_EKPO_EKET-WEMNG.
    ENDLOOP.

    LOOP AT IT_EKPO1 INTO WA_EKPO1 WHERE MATNR = WA_MARA_MARD-MATNR AND WERKS = WA_MARA_MARD-WERKS.

      WA_FINAL-MENGE4 = WA_FINAL-MENGE4 + WA_EKPO1-MENGE.
      WA_FINAL-PO_VAL1 = WA_FINAL-PO_VAL1 + WA_EKPO1-BRTWR.

    ENDLOOP.

    CLEAR WA_FINAL-PEND_PO_QTY.
    WA_FINAL-PEND_PO_QTY = WA_FINAL-MENGE2 - WA_FINAL-MENGE3 - WA_FINAL-MENGE4.
    WA_FINAL-PO_VAL2 =  WA_FINAL-PO_VAL - WA_FINAL-PO_VAL1.

    WA_FINAL-PO_VALUE = WA_FINAL-PO_VAL2 - WA_FINAL-GRN_VALUE.

    IF WA_FINAL-PEND_PO_QTY LT 0.
      WA_FINAL-PEND_PO_QTY = 0.
    ENDIF.

    IF WA_FINAL-PO_VALUE LT 0.
      WA_FINAL-PO_VALUE = 0.
    ENDIF.

    CLEAR WA_FINAL-FREE_STOCK.
    WA_FINAL-FREE_STOCK =  WA_FINAL-LABST -  WA_FINAL-OPEN_QTY.
    IF WA_FINAL-FREE_STOCK LT 0.
      WA_FINAL-FREE_STOCK = 0.
    ENDIF.

    CLEAR WA_FINAL-SO_FALL_QTY.
    WA_FINAL-SO_FALL_QTY =  WA_FINAL-OPEN_QTY - WA_FINAL-LABST - WA_FINAL-TRAN_QTY .
    IF WA_FINAL-SO_FALL_QTY LT 0.
      WA_FINAL-SO_FALL_QTY = 0.
    ENDIF.

    CLEAR WA_FINAL-INDENT_QTY.
    WA_FINAL-INDENT_QTY =  WA_FINAL-OPEN_QTY - ( WA_FINAL-LABST + WA_FINAL-PEND_PO_QTY ).

    IF WA_FINAL-INDENT_QTY LT 0.
      WA_FINAL-INDENT_QTY = 0.
    ENDIF.


    CLEAR: LV_LINES, LS_MATTXT.
    REFRESH LV_LINES.
    LV_NAME = WA_MARA_MARD-MATNR.
    CALL FUNCTION 'READ_TEXT'
      EXPORTING
        CLIENT                  = SY-MANDT
        ID                      = 'GRUN'
        LANGUAGE                = SY-LANGU
        NAME                    = LV_NAME
        OBJECT                  = 'MATERIAL'
      TABLES
        LINES                   = LV_LINES
      EXCEPTIONS
        ID                      = 1
        LANGUAGE                = 2
        NAME                    = 3
        NOT_FOUND               = 4
        OBJECT                  = 5
        REFERENCE_CHECK         = 6
        WRONG_ACCESS_TO_ARCHIVE = 7
        OTHERS                  = 8.
    IF SY-SUBRC <> 0.
* IMPLEMENT SUITABLE ERROR HANDLING HERE
    ENDIF.
    IF NOT LV_LINES IS INITIAL.
      LOOP AT LV_LINES INTO WA_LINES.
        IF NOT WA_LINES-TDLINE IS INITIAL.
          CONCATENATE WA_FINAL-MATTXT WA_LINES-TDLINE INTO WA_FINAL-MATTXT SEPARATED BY SPACE.
        ENDIF.
      ENDLOOP.
      CONDENSE WA_FINAL-MATTXT.
    ENDIF.

    WA_FINAL-OPEN_QTY_V     = WA_FINAL-OPEN_QTY    * WA_FINAL-VALUE.
    WA_FINAL-KULAB_V        = WA_FINAL-KULAB       * WA_FINAL-VALUE.
    WA_FINAL-FREE_STOCK_V   = WA_FINAL-FREE_STOCK  * WA_FINAL-VALUE.
*    wa_final-TRAN_QTY_V     = wa_final-TRAN_QTY    * wa_final-value.
    WA_FINAL-SO_FALL_QTY_V  = WA_FINAL-SO_FALL_QTY * WA_FINAL-VALUE.
    WA_FINAL-PEND_PO_QTY_V  = WA_FINAL-PEND_PO_QTY * WA_FINAL-VALUE.
    WA_FINAL-INDENT_QTY_V   = WA_FINAL-INDENT_QTY  * WA_FINAL-VALUE.
    WA_FINAL-OPEN_INV_V     = WA_FINAL-OPEN_INV    * WA_FINAL-VALUE.
    WA_FINAL-UN_QTY  = WA_FINAL-UN_QTY + WA_FINAL-KULAB.
*    wa_final-UN_VAL  = wa_final-UN_VAL + wa_final-KULAB_V.

    WA_FINAL-LABST_V = WA_FINAL-LABST_V - WA_FINAL-KULAB_V.



    APPEND WA_FINAL TO IT_FINAL.
    CLEAR : WA_FINAL,LS_FINAL,WA_DATA.
  ENDLOOP.

  IF P_DOWN = 'X'.
    LOOP AT IT_FINAL INTO WA_FINAL.
      LS_FINAL-MATNR       = WA_FINAL-MATNR  .
      LS_FINAL-MATTXT      = WA_FINAL-MATTXT.
      LS_FINAL-WRKST       = WA_FINAL-WRKST  .
      LS_FINAL-BRAND       = WA_FINAL-BRAND  .
      LS_FINAL-ZSERIES     = WA_FINAL-ZSERIES.
      LS_FINAL-ZSIZE       = WA_FINAL-ZSIZE  .
      LS_FINAL-MOC         = WA_FINAL-MOC    .
      LS_FINAL-TYPE        = WA_FINAL-TYPE   .
      LS_FINAL-OPEN_QTY    = WA_FINAL-OPEN_QTY.
      LS_FINAL-PRICE       = WA_FINAL-PRICE     .
      LS_FINAL-OPEN_QTY_V  = WA_FINAL-OPEN_QTY_V     .
      LS_FINAL-LABST       = WA_FINAL-LABST.
      LS_FINAL-LABST_V     = WA_FINAL-LABST_V        .
      LS_FINAL-KULAB       = WA_FINAL-KULAB.
      LS_FINAL-KULAB_V     = WA_FINAL-KULAB_V        .
      LS_FINAL-FREE_STOCK  = WA_FINAL-FREE_STOCK.
      LS_FINAL-FREE_STOCK_V  = WA_FINAL-FREE_STOCK_V   .
      LS_FINAL-TRAN_QTY      = WA_FINAL-TRAN_QTY.
      LS_FINAL-TRAN_QTY_V    = WA_FINAL-TRAN_QTY_V     .
      LS_FINAL-SO_FALL_QTY   = WA_FINAL-SO_FALL_QTY.
      LS_FINAL-SO_FALL_QTY_V = WA_FINAL-SO_FALL_QTY_V  .
      LS_FINAL-PEND_PO_QTY   = WA_FINAL-PEND_PO_QTY.
      LS_FINAL-PO_VALUE      = WA_FINAL-PO_VALUE  .
      LS_FINAL-OPEN_INV      = WA_FINAL-OPEN_INV.
      LS_FINAL-AMOUNT        = WA_FINAL-AMOUNT   .
      LS_FINAL-VALUE         = WA_FINAL-VALUE   .
      LS_FINAL-WERKS         = WA_FINAL-WERKS   .

      LS_FINAL-REF = SY-DATUM.


      CALL FUNCTION 'CONVERSION_EXIT_IDATE_OUTPUT'
        EXPORTING
          INPUT  = LS_FINAL-REF
        IMPORTING
          OUTPUT = LS_FINAL-REF.

      CONCATENATE LS_FINAL-REF+0(2) LS_FINAL-REF+2(3) LS_FINAL-REF+5(4)
                      INTO LS_FINAL-REF SEPARATED BY '-'.




      APPEND LS_FINAL TO LT_FINAL.
      CLEAR LS_FINAL.
    ENDLOOP.
  ENDIF.
ENDFORM.

FORM FCAT .

  PERFORM BUILD_FC USING  '1' PR_COUNT 'MATNR'                 'Material Code'             'IT_FINAL'  '20'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'MATTXT'                'Material Description'      'IT_FINAL'  '50' .
  PERFORM BUILD_FC USING  '1' PR_COUNT 'WRKST'                 'USA Material Code'         'IT_FINAL'  '20'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'BRAND'                 'Brand'                     'IT_FINAL'  '5'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'ZSERIES'               'Series'                    'IT_FINAL'  '5'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'ZSIZE'                 'Size'                      'IT_FINAL'  '5'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'MOC'                   'MOC'                       'IT_FINAL'  '5'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'TYPE'                  'Type'                      'IT_FINAL'  '5'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'OPEN_QTY'              'Pending SO '               'IT_FINAL'  '20'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'PRICE'                 'Pending So Value'          'IT_FINAL'  '20'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'UN_QTY'                'Unrestricted Quantity'     'IT_FINAL'  '20'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'UN_VAL'                'Unrestricted Value'          'IT_FINAL'  '20'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'OPEN_QTY_V'            'Pending So Sales Total'    'IT_FINAL'  '20'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'LABST'                 'Stock In Hand'             'IT_FINAL'  '15'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'LABST_V'               'Stock In Hand Value'       'IT_FINAL'  '20'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'KULAB'                 'Consignment Stock'         'IT_FINAL'  '20'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'KULAB_V'               'Consignment Stock Value'   'IT_FINAL'  '20'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'FREE_STOCK'            'Free Stock'                'IT_FINAL'  '15'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'FREE_STOCK_V'          'Free Stock Value'          'IT_FINAL'  '15'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'TRAN_QTY'              'Transit Qty'               'IT_FINAL'  '15'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'TRAN_QTY_V'            'Transit Value'             'IT_FINAL'  '15'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'SO_FALL_QTY'           'SO Short Fall Qty'         'IT_FINAL'  '20'.
*  PERFORM build_fc USING  '1' pr_count 'SO_FALL_QTY_V'         'SO Short Fall Qty Value'   'IT_FINAL'  '20'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'PEND_PO_QTY'           'Pending PO Qty'            'IT_FINAL'  '20'.
*  PERFORM build_fc USING  '1' pr_count 'PO_VALUE'              'Pending PO Amount'         'IT_FINAL'  '20'.
*  PERFORM build_fc USING  '1' pr_count 'INDENT_QTY'            'Indent Qty'                'IT_FINAL'  '20'.
*  PERFORM build_fc USING  '1' pr_count 'INDENT_QTY_V'          'Indent Qty Value'          'IT_FINAL'  '20'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'OPEN_INV'              'Open Invoice Qty'          'IT_FINAL'  '20'.
*  PERFORM build_fc USING  '1' pr_count 'OPEN_INV_V'            'Open Invoice Qty Value'    'IT_FINAL'  '20'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'AMOUNT'                'Last Item Price'           'IT_FINAL'  '20'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'VALUE'                 'Moving Price'              'IT_FINAL'  '20'.
  PERFORM BUILD_FC USING  '1' PR_COUNT 'WERKS'                 'Plant'                     'IT_FINAL'  '10'.


ENDFORM.

FORM DISPLAY_DATA.
  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      I_CALLBACK_PROGRAM     = SY-REPID
      I_CALLBACK_TOP_OF_PAGE = 'TOP-OF-PAGE'
      IT_FIELDCAT            = GT_FIELDCAT
      I_SAVE                 = 'X'
    TABLES
      T_OUTTAB               = IT_FINAL
*   EXCEPTIONS
*     PROGRAM_ERROR          = 1
*     OTHERS                 = 2
    .
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.
  IF P_DOWN = 'X'.

    PERFORM DOWNLOAD.
*    PERFORM gui_download.
  ENDIF.
ENDFORM.

FORM BUILD_FC  USING        PR_ROW TYPE I
                            PR_COUNT TYPE I
                            PR_FNAME TYPE STRING
                            PR_TITLE TYPE STRING
                            PR_TABLE TYPE SLIS_TABNAME
                            PR_LENGTH TYPE STRING.

  PR_COUNT = PR_COUNT + 1.
  GS_FIELDCAT-ROW_POS   = PR_ROW.
  GS_FIELDCAT-COL_POS   = PR_COUNT.
  GS_FIELDCAT-FIELDNAME = PR_FNAME.
  GS_FIELDCAT-SELTEXT_L = PR_TITLE.
  GS_FIELDCAT-TABNAME   = PR_TABLE.
  GS_FIELDCAT-OUTPUTLEN = PR_LENGTH.

  APPEND GS_FIELDCAT TO GT_FIELDCAT.
  CLEAR GS_FIELDCAT.

ENDFORM.

FORM TOP-OF-PAGE.

*  ALV Header declarations
  DATA: T_HEADER      TYPE SLIS_T_LISTHEADER,
        WA_HEADER     TYPE SLIS_LISTHEADER,
        T_LINE        LIKE WA_HEADER-INFO,
        LD_LINES      TYPE I,
        LD_LINESC(10) TYPE C.

*  Title
  WA_HEADER-TYP  = 'H'.
  WA_HEADER-INFO = 'Stock Bank Report '.
  APPEND WA_HEADER TO T_HEADER.
  CLEAR WA_HEADER.



*  Date
*  wa_header-typ  = 'S'.
*  wa_header-key  = 'Run Date : '.
*  CONCATENATE wa_header-info sy-datum+6(2) '.' sy-datum+4(2) '.'
*                      sy-datum(4) INTO wa_header-info.
*  APPEND wa_header TO t_header.
*  CLEAR: wa_header.
*
**  Time
*  wa_header-typ  = 'S'.
*  wa_header-key  = 'Run Time: '.
*  CONCATENATE wa_header-info sy-timlo(2) ':' sy-timlo+2(2) ':'
*                      sy-timlo+4(2) INTO wa_header-info.
*  APPEND wa_header TO t_header.
*  CLEAR: wa_header.

*   Total No. of Records Selected
  DESCRIBE TABLE IT_FINAL LINES LD_LINES.
  LD_LINESC = LD_LINES.

  CONCATENATE 'Total No. of Records Selected: ' LD_LINESC
     INTO T_LINE SEPARATED BY SPACE.

  WA_HEADER-TYP  = 'A'.
  WA_HEADER-INFO = T_LINE.
  APPEND WA_HEADER TO T_HEADER.
  CLEAR: WA_HEADER, T_LINE.

  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = T_HEADER.
ENDFORM.                    " top-of-page



*****************************************Download logic***************************************************

FORM DOWNLOAD .
  TYPE-POOLS TRUXS.
  DATA: IT_CSV TYPE TRUXS_T_TEXT_DATA,
        WA_CSV TYPE LINE OF TRUXS_T_TEXT_DATA,
        HD_CSV TYPE LINE OF TRUXS_T_TEXT_DATA.

*  DATA: lv_folder(150).
  DATA: LV_FILE(30).
  DATA: LV_FULLFILE TYPE STRING,
        LV_DAT(10),
        LV_TIM(4).
  DATA: LV_MSG(80).

  CALL FUNCTION 'SAP_CONVERT_TO_TXT_FORMAT'
*   EXPORTING
*     I_FIELD_SEPERATOR          =
*     I_LINE_HEADER              =
*     I_FILENAME                 =
*     I_APPL_KEEP                = ' '
    TABLES
      I_TAB_SAP_DATA       = LT_FINAL
    CHANGING
      I_TAB_CONVERTED_DATA = IT_CSV
    EXCEPTIONS
      CONVERSION_FAILED    = 1
      OTHERS               = 2.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.

  PERFORM CVS_HEADER USING HD_CSV.

*  lv_folder = 'D:\usr\sap\DEV\D00\work'.

*  IF plant = 'US01'.
  LV_FILE = 'ZUS_STOCK_BANK_US01.TXT'.
*  ENDIF.

  CONCATENATE P_FOLDER '/' SY-DATUM SY-UZEIT LV_FILE
    INTO LV_FULLFILE.

  WRITE: / 'Material Stock Bank Report started on', SY-DATUM, 'at', SY-UZEIT.
  OPEN DATASET LV_FULLFILE
    FOR OUTPUT IN TEXT MODE ENCODING DEFAULT.  "NON-UNICODE.
  IF SY-SUBRC = 0.
DATA lv_string_1239 TYPE string.
DATA lv_crlf_1239 TYPE string.
lv_crlf_1239 = cl_abap_char_utilities=>cr_lf.
lv_string_1239 = hd_csv.
LOOP AT it_csv INTO wa_csv.
CONCATENATE lv_string_1239 lv_crlf_1239 wa_csv INTO lv_string_1239.
  CLEAR: wa_csv.
ENDLOOP.
TRANSFER lv_string_1239 TO lv_fullfile.
    CONCATENATE 'File' LV_FULLFILE 'downloaded' INTO LV_MSG SEPARATED BY SPACE.
    MESSAGE LV_MSG TYPE 'S'.
  ENDIF.


**********************************SQL UPLOAD FILE*************************************

  CALL FUNCTION 'SAP_CONVERT_TO_TXT_FORMAT'
*   EXPORTING
*     I_FIELD_SEPERATOR          =
*     I_LINE_HEADER              =
*     I_FILENAME                 =
*     I_APPL_KEEP                = ' '
    TABLES
      I_TAB_SAP_DATA       = LT_FINAL
    CHANGING
      I_TAB_CONVERTED_DATA = IT_CSV
    EXCEPTIONS
      CONVERSION_FAILED    = 1
      OTHERS               = 2.
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.

  PERFORM CVS_HEADER USING HD_CSV.

*  lv_folder = 'D:\usr\sap\DEV\D00\work'.

*  IF plant = 'US01'.
  LV_FILE = 'ZUS_STOCK_BANK_US01.TXT'.
*  ENDIF.

  CONCATENATE P_FOLDER '/' LV_FILE
    INTO LV_FULLFILE.

  WRITE: / 'Material Stock Bank Report started on', SY-DATUM, 'at', SY-UZEIT.
  OPEN DATASET LV_FULLFILE
    FOR OUTPUT IN TEXT MODE ENCODING DEFAULT.  "NON-UNICODE.
  IF SY-SUBRC = 0.
DATA lv_string_1279 TYPE string.
DATA lv_crlf_1279 TYPE string.
lv_crlf_1279 = cl_abap_char_utilities=>cr_lf.
lv_string_1279 = hd_csv.
LOOP AT it_csv INTO wa_csv.
CONCATENATE lv_string_1279 lv_crlf_1279 wa_csv INTO lv_string_1279.
  CLEAR: wa_csv.
ENDLOOP.
TRANSFER lv_string_1279 TO lv_fullfile.
    CONCATENATE 'File' LV_FULLFILE 'downloaded' INTO LV_MSG SEPARATED BY SPACE.
    MESSAGE LV_MSG TYPE 'S'.
  ENDIF.



ENDFORM.
*&---------------------------------------------------------------------*
*&      Form  CVS_HEADER
*&---------------------------------------------------------------------*
*       text
*----------------------------------------------------------------------*
*      -->P_HD_CSV  text
*----------------------------------------------------------------------*
FORM CVS_HEADER  USING    PD_CSV.
  DATA: L_FIELD_SEPERATOR.
  L_FIELD_SEPERATOR = CL_ABAP_CHAR_UTILITIES=>HORIZONTAL_TAB.
  CONCATENATE 'Material Code'
              'Material Description'
              'USA Material Code'
              'Brand'
              'Series'
              'Size'
              'MOC'
              'Type'
              'Pending SO'
              'Pending So Value'
              'Unrestricted Quantity'
              'Unrestricted Value'
              'Pending So Sales Total'
              'Stock In Hand'
              'Stock In Hand Value'
              'Consignment Stock'
              'Consignment Stock Value'
              'Free Stock'
              'Free Stock Value'
              'Transit Qty'
              'Transit Value'
              'SO Short Fall Qty'
              'SO Short Fall Qty Value'
              'Pending PO Qty'
              'Pending PO Amount'
              'Open Invoice Qty'
              'Last Item Price'
              'Moving Price'
              'Refresh File Date'
              'Plant'
               INTO PD_CSV
               SEPARATED BY L_FIELD_SEPERATOR.

ENDFORM.


**********************************************************************************************************
