TYPES:BEGIN OF ty_lips,
      VBELN TYPE lips-VBELN,
      POSNR TYPE lips-POSNR,
      MATNR TYPE lips-MATNR,
      WERKS TYPE lips-WERKS,
      LFIMG TYPE lips-LFIMG,
      VGBEL TYPE lips-VGBEL,
      VGPOS TYPE lips-VGPOS,
      END OF ty_lips,

      BEGIN OF ty_adr6,
      ADDRNUMBER TYPE adr6-ADDRNUMBER,
      CONSNUMBER TYPE adr6-CONSNUMBER,
      SMTP_ADDR  TYPE adr6-SMTP_ADDR,
      END OF ty_adr6,

      BEGIN OF ty_vbap,
      vbeln TYPE vbap-vbeln,
      posnr TYPE vbap-posnr,
      kwmeng TYPE vbap-kwmeng,
      lfrel  TYPE vbap-lfrel,
      END OF ty_vbap,


      BEGIN OF TY_VBFA,
      VBELV TYPE VBFA-vbELV,
      POSNV TYPE VBFA-posnv,
      VBELN TYPE VBFA-vbeln,
      POSNN TYPE VBFA-POSNN,
      VBTYP_N TYPE VBFA-VBTYP_N,
      END OF TY_VBFA,

      BEGIN OF TY_VBFA1,
      VBELV  TYPE VBFA-vbELV,
      POSNV  TYPE VBFA-posnv,
      VBELN  TYPE VBFA-vbeln,
      POSNN  TYPE VBFA-POSNN,
      VBTYP_N TYPE VBFA-VBTYP_N,
      TAQUI  TYPE VBFA-TAQUI,
      END OF TY_VBFA1.
types : begin of ty_likp,
        vbeln type likp-vbeln,
        bldat type likp-bldat,
       end of ty_likp.
