PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZUS_HIST_DATA-ZITEM .
    FIELD ZUS_HIST_DATA-ZSERIES .
    FIELD ZUS_HIST_DATA-ZSIZE .
    FIELD ZUS_HIST_DATA-HAND_QTY .
    FIELD ZUS_HIST_DATA-SO_QTY .
    FIELD ZUS_HIST_DATA-AVAIL_QTY .
    FIELD ZUS_HIST_DATA-PO_QTY .
    FIELD ZUS_HIST_DATA-TRANSIT_QTY .
    FIELD ZUS_HIST_DATA-TOTAL_SOLD .
    FIELD ZUS_HIST_DATA-TOTAL_SOLD1 .
    FIELD ZUS_HIST_DATA-TOTAL_SOLD2 .
    FIELD ZUS_HIST_DATA-TOTAL_PUR .
    FIELD ZUS_HIST_DATA-TOTAL_PUR1 .
    FIELD ZUS_HIST_DATA-TOTAL_PUR2 .
    FIELD ZUS_HIST_DATA-SALES .
    FIELD ZUS_HIST_DATA-PURCHASE .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZUS_HIST_DATA-ZITEM .
  module detail_pai.
 endchain.
