TYPES:BEGIN OF TY_FINAL,
*      VBELN TYPE VBAP-VBELN,
      POSNR TYPE VBAP-POSNR,
      MATNR TYPE VBAP-MATNR,
      BRGEW TYPE VBAP-BRGEW,
      NETPR TYPE VBAP-NETPR,
      NETWR TYPE VBAP-NETWR,
      KWMENG TYPE VBAP-KWMENG,
      ULOC TYPE KONV-KWERT,
      USTA TYPE KONV-KWERT,
      UCOU TYPE KONV-KWERT,
      UFR1 TYPE KONV-KWERT,
      UHF1 TYPE KONV-KWERT,
      USC1 TYPE KONV-KWERT,
      UMC1 TYPE KONV-KWERT,
      UOTH TYPE KONV-KWERT,
      END OF TY_FINAL,


      BEGIN OF TY_KONV,
      KNUMV TYPE KONV-KNUMV,
      KPOSN TYPE KONV-KPOSN,
      KSCHL TYPE KONV-KSCHL,
      KBETR TYPE KONV-KBETR,
      KWERT TYPE KONV-KWERT,
      END OF TY_KONV,

      BEGIN OF ty_adr6,
      ADDRNUMBER TYPE adr6-ADDRNUMBER,
      CONSNUMBER TYPE adr6-CONSNUMBER,
      SMTP_ADDR  TYPE adr6-SMTP_ADDR,
      END OF ty_adr6.
















